spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: oris-semester-work
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/template/
    suffix: .html
    encoding: UTF-8
    mode: HTML
logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.security: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/app.log

jwt:
  admin-username: ${ADMIN_USERNAME}
  admin-password: ${ADMIN_PASSWORD}
  secret: ${JWT_SECRET}

zoom:
  client-id:${ZOOM_CLIENT_ID}
  client-secret:${ZOOM_CLIENT_SECRET}
  account-id:${ZOOM_ACCOUNT_ID}

comment-service:
  host: "localhost"
  port: 8081